plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
branches:
  - name: +([0-9])?(.{+([0-9]),x}).x
  - name: main
  - name: beta
    prerelease: true
  - name: next
    prerelease: true
