site_name: GCP Nuke
site_url: https://ekristen.github.io/gcp-nuke
site_author: Erik Kristensen
site_description: >-
 GCP Nuke is a tool to clean up your GCP project by nuking (deleting) all resources within it.

repo_name: ekristen/gcp-nuke
repo_url: https://github.com/ekristen/gcp-nuke

copyright: Copyright &copy; 2024 - Erik Kristensen

site_dir: public

# Configuration
theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  features:
    - navigation.footer
    - navigation.indexes
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - toc.follow
    - toc.integrate
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - search.highlight
    - search.share
    - search.suggest

# Plugins
plugins:
  - search

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

# Page tree
nav:
  - Getting Started:
      - Overview: index.md
      - Warning: warning.md
      - Install: installation.md
      - Quick Start: quick-start.md
  - Features:
      - Overview: features/overview.md
      - Global Filters: features/global-filters.md
      - All Regions: features/all-regions.md
      - Signed Binaries: features/signed-binaries.md
  - CLI:
      - Usage: cli-usage.md
      - Options: cli-options.md
      - Experimental: cli-experimental.md
  - Config:
      - Overview: config.md
      - Filtering: config-filtering.md
      - Presets: config-presets.md
  - Development:
      - Overview: development.md
      - Contributing: contributing.md
      - Standards: standards.md
      - Resources: resources.md
      - Releases: releases.md
      - Testing: testing.md